##################################################################################################
# Details service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: details
  labels:
    app: details
    service: details
spec:
  ports:
  - port: 8081
    name: grpc
  selector:
    app: details
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-details
  labels:
    account: details
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-v1
  labels:
    app: details
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: v1
  template:
    metadata:
      labels:
        app: details
        version: v1
    spec:
      serviceAccountName: bookinfo-details
      containers:
      - name: details
        image: xzhu0027/bookinfo_grpc_details:latest
        command: ["/go/bin/cmd"]
        args: ["details"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
---
##################################################################################################
# Ratings service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    app: ratings
    service: ratings
spec:
  ports:
  - port: 8082
    name: grpc
  selector:
    app: ratings
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-ratings
  labels:
    account: ratings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-v1
  labels:
    app: ratings
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      version: v1
  template:
    metadata:
      labels:
        app: ratings
        version: v1
    spec:
      serviceAccountName: bookinfo-ratings
      containers:
      - name: ratings
        image: xzhu0027/bookinfo_grpc_ratings:latest
        command: ["/go/bin/cmd"]
        args: ["ratings"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
---
##################################################################################################
# Reviews service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: reviews
  labels:
    app: reviews
    service: reviews
spec:
  # sessionAffinity: ClientIP
  ports:
  - port: 8083
    name: grpc
  selector:
    app: reviews
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-reviews
  labels:
    account: reviews
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v1
  labels:
    app: reviews
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: reviews
        image: xzhu0027/bookinfo_grpc_reviews:latest
        command: ["/go/bin/cmd"]
        args: ["reviews"]
        imagePullPolicy: IfNotPresent
        env:
        - name: REVIEWS_VERSION
          value: "v1"
        ports:
        - containerPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2
  labels:
    app: reviews
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v2
  template:
    metadata:
      labels:
        app: reviews
        version: v2
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: reviews
        image: xzhu0027/bookinfo_grpc_reviews:latest
        command: ["/go/bin/cmd"]
        args: ["reviews"]
        imagePullPolicy: IfNotPresent
        env:
        - name: REVIEWS_VERSION
          value: "v2"
        ports:
        - containerPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v3
  labels:
    app: reviews
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v3
  template:
    metadata:
      labels:
        app: reviews
        version: v3
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: reviews
        image: xzhu0027/bookinfo_grpc_reviews:latest
        command: ["/go/bin/cmd"]
        args: ["reviews"]
        imagePullPolicy: IfNotPresent
        env:
        - name: REVIEWS_VERSION
          value: "v3"
        ports:
        - containerPort: 8083
---
##################################################################################################
# Productpage services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
spec:
  clusterIP: 10.96.88.88
  ports:
  - port: 8080
    name: http
  selector:
    app: productpage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-productpage
  labels:
    account: productpage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-v1
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      serviceAccountName: bookinfo-productpage
      containers:
      - name: productpage
        image: xzhu0027/bookinfo_grpc_productpage
        command: ["/go/bin/cmd"]
        args: ["productpage"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---